blank_issues_enabled: false
contact_links:
  - name: ğŸ¤š Discord Chat
    url: https://discord.surmon.me
    about: Ask questions and discuss with other users in real time
  - name: â¤ï¸â€ğŸ”¥ Sponsor
    url: https://github.com/sponsors/surmon-china
    about: Please consider supporting me via GitHub Sponsors
